### PR TITLE
fix #387: Feature by Author

### LINKED ISSUE #387: Feature by Author
Would be great to add an "Author" filter similar to "Categories" and "Tags" but for Authors, including PublishPress Authors

That would allow you show all the recent posts from one Author

### PR DESCRIPTION
**Pull request by contactashish13**
#387 

image

### CODE REVIEW

**Comment by stevejburge** [comment]
Awesome, thanks @contactashish13

**Comment by htmgarcia** [comment]
@contactashish13 please update the PR

**Comment by contactashish13** [comment]
@htmgarcia done

**Comment by htmgarcia** [comment]
@contactashish13 one last fix. Authors coming from PublishPress Authors are not listed. Please add support for it.

**Comment by contactashish13** [comment]
@htmgarcia Sorry, I didn't realize you could add a non-WP user through that plugin. I have added support for such authors as well.

Can I suggest a change in the authors plugin whenever possible? [This portion](https://github.com/publishpress/PublishPress-Blocks/pull/419/commits/8a7c5b097524574b60d1c0ecfafb73f190f42135#diff-e80a99cd2188607f6b623bf165db1f288dbf4b55a44cb5d287d2bf3682907d05R716-R722) can be encapsulated in that plugin so that one doesn't have to do `get_by_user_id` or `get_by_term_id`. Maybe the constructor can be changed to do this if the `id` is negative?

**Comment by htmgarcia** [comment]
Thanks @contactashish13 !

**Comment by htmgarcia** [comment]
cc @andergmartins 

> @htmgarcia Sorry, I didn't realize you could add a non-WP user through that plugin. I have added support for such authors as well.
> 
> Can I suggest a change in the authors plugin whenever possible? [This portion](https://github.com/publishpress/PublishPress-Blocks/pull/419/commits/8a7c5b097524574b60d1c0ecfafb73f190f42135#diff-e80a99cd2188607f6b623bf165db1f288dbf4b55a44cb5d287d2bf3682907d05R716-R722) can be encapsulated in that plugin so that one doesn't have to do `get_by_user_id` or `get_by_term_id`. Maybe the constructor can be changed to do this if the `id` is negative?

**Comment by andergmartins** [comment]
> @htmgarcia Sorry, I didn't realize you could add a non-WP user through that plugin. I have added support for such authors as well.
> 
> Can I suggest a change in the authors plugin whenever possible? [This portion](https://github.com/publishpress/PublishPress-Blocks/pull/419/commits/8a7c5b097524574b60d1c0ecfafb73f190f42135#diff-e80a99cd2188607f6b623bf165db1f288dbf4b55a44cb5d287d2bf3682907d05R716-R722) can be encapsulated in that plugin so that one doesn't have to do `get_by_user_id` or `get_by_term_id`. Maybe the constructor can be changed to do this if the `id` is negative?

Sorry, I missed that notification. That is a good suggestion, but we would have a problem guaranteeing backward compatibility with the current logic in the constructor.

It makes sense to accept negative integers for identifying terms there, but considering it already accepts term IDs as positive, if we change that for using positive integers for User IDs and negative integers for Term IDs, we have a problem if anyone is using the constructor passing the term ID. It would be treated as user ID, and returning wrong results.

**Pull request merged**
