### PR TITLE
fix #407: include/exclude specific posts

### LINKED ISSUE #407: Exclude specific posts
We had a request to include or exclude specific post IDs from the Recent Posts display

### PR DESCRIPTION
**Pull request by contactashish13**
#407 

image

@htmgarcia I don't know why the query returns duplicate posts when `include` was used but I couldn't figure it out. I am not fond of the [workaround](https://github.com/publishpress/PublishPress-Blocks/compare/develop...contactashish13:issue-407?expand=1#diff-f85cce7f18a74204bcf961dd3f0982baf508168c55d450f912234978de5538b4R290-R291) but there was no other way I could find. Maybe you can help?

### CODE REVIEW

**Comment by htmgarcia** [comment]
@contactashish13 please update the PR

**Comment by contactashish13** [comment]
@htmgarcia done

**Comment by htmgarcia** [comment]
Thanks @contactashish13 ! 

Under a scenario with 2 posts excluded I found the issues below that needs a fix, please:

1. When loading the block in editor, before seeing the block 100% loaded I can read the "No posts found" message for a second. 

2. If I exclude a couple of posts, works fine. However if I try to exclude a post that replaced the first excludes, it doesn't work. The title doesn't show up even reloading the editor.
Screen Shot 2021-04-09 at 10 26 45

3. Frontend and admin doesn't show the same content. One of the posts is not excluded in frontend.

### Admin

Screen Shot 2021-04-09 at 10 35 53


### Frontend

Screen Shot 2021-04-09 at 10 36 18

4. "Include these posts" doesn't show any suggestion when typing a post title.

**Comment by contactashish13** [comment]
@htmgarcia I was able to fix the first issue but was not able to reproduce the others. I have attached a screen recording of my testing. Maybe I'm missing some critical step?

https://user-images.githubusercontent.com/12953439/114342632-cc8be380-9b79-11eb-9a8c-9f56b08f3196.mp4

**Comment by htmgarcia** [comment]
@contactashish13 1 and 4 are solved. 2 and 3 still needs some work.
I realized when I was editing the block the results were looking fine in the editor but not in frontend, however once I refresh the editor, the excluded posts are not working:
Screen Shot 2021-04-12 at 19 13 50


@stevejburge with "Include these posts" do we want to display:
A) Only the posts listed here?
B) The posts based on the filters (categories, tags, author) plus the ones from "Include these posts"?

Current result follows **A** approach

### When "Include these posts" is blank
Screen Shot 2021-04-12 at 18 56 52

### When "Include these posts" mention one of the posts loaded by default
Screen Shot 2021-04-12 at 18 57 19

**Comment by contactashish13** [comment]
@htmgarcia when I refresh the editor at my end that excludes some posts, it works as expected. Here are my steps, maybe you can tell me if I'm missing something:
- create new post
- exclude M posts out of N
- I see N-M posts in the editor
- save
- refresh the editor
- I see only N-M posts on both editor and frontend

**Comment by stevejburge** [comment]
@contactashish13 @htmgarcia Great work guys.

I think we launch like this. 

In the future, we can consider some "and/or" settings for the filters

**Comment by htmgarcia** [comment]
@contactashish13 sorry, still having the same issue while excluding posts. 

- Remove "Include these posts" setting. 
- Update the PR
- Let's try to figure out the "Exclude these posts", please.

**Comment by contactashish13** [comment]
@htmgarcia I have removed support for include but that does not change the behavior at my end. I still cannot reproduce the issue you see with excluding posts so I'm not sure how to fix it when I cannot reproduce it. If you can provide access to an environment where I can replicate this behavior, it may be more helpful in debugging.

**Comment by htmgarcia** [comment]
@contactashish13 I created a test site and emailed you the details.

**Comment by htmgarcia** [comment]
@contactashish13 don't forget to update the PR. btw, "Recent Posts" block was renamed to "Content Display"

**Comment by contactashish13** [comment]
@htmgarcia so the problem was the difference between our posts. My posts had the same slugs as their titles but yours did not. I have fixed the issue (on the instance as well). Can you please test?

To populate suggestions properly I have also removed `per_page` from the query that fetches suggestions. This is to cater to the following type of scenario:
- Let's assume there are 100 posts in WP
- User says "display 4 posts" with no other filters, so we show 4 posts only. Suggestions for exclude will also contain only those 4 posts because we are using the same `per_page` parameter for fetching suggestions.
- the user excludes the 4 posts that are current showing, thereby showing 4 other posts. Suggestions **still** contain only the original 4 posts and not the 4 posts that are now displayed

I also found another error that I fixed, probably related to some other changes in the code:

```
Undefined variable: postThumbCaption in plugins\advanced-gutenberg\assets\blocks\recent-posts\block.php on line 164
```

**Comment by htmgarcia** [comment]
Thanks @contactashish13 ! The last commit solved the issue.

Good catch on the undefined variable. That was me.

**Pull request merged**
