### PR TITLE
add support for tags

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by contactashish13** [comment]
@htmgarcia can you please review this?

**Comment by contactashish13** [comment]
@htmgarcia I got these errors during development and I fixed them before my commits. Just now I tried to create a new post and it works perfectly. I get none of the errors. Maybe it is a specific scenario?

**Comment by htmgarcia** [comment]
@contactashish13 in order to reproduce the issues, please follow these steps:

1. Install PublishPress Blocks 2.5.7
2. Create a new page or post
3. Insert a Recent Posts block
4. Be sure to choose at least one category and publish
5. Preview the page in frontend
6. Update to the version that includes your changes
7. Refresh the page or post created in step 2 in frontend and admin to compare

**Comment by contactashish13** [comment]
@htmgarcia thanks! Have fixed the issue. Sorry about that. I will try to remember to test the upgrade path before creating the PR :)

**Comment by htmgarcia** [comment]
@contactashish13 that solved both issues. Thanks! 

A last request, please move "Tags" field below "Categories"
Screen Shot 2021-03-11 at 10 35 01

**Comment by contactashish13** [comment]
That may not be possible to do as categories, number of posts and order by are part of the same component and I've used a separate component for tags. What do you think?

On Mar 11, 2021, 22:07, at 22:07, "Valentín" ***@***.***> wrote:
***@***.*** that solved both issues. Thanks!

**Comment by htmgarcia** [comment]
@contactashish13 thanks for the clarification!

**Pull request merged**
