### PR TITLE
Support for PP Authors

### PR DESCRIPTION
**Pull request by contactashish13**
#143 

Assuming a post contains multiple authors:

image

The post edit screen will look like this

image

and the front end will look like this

image

It will default to the default WP implementation if the Authors plugin is not active

### CODE REVIEW

**Comment by contactashish13** [comment]
@htmgarcia can you please review this?

**Comment by htmgarcia** [comment]
Thanks @contactashish13!

Please use 'get_multiple_authors' instead of 'get_coauthors' - https://github.com/publishpress/PublishPress-Blocks/pull/353/commits/5bf24b4687aa57d3eb1a8e17777869877f1a3e5d#diff-e80a99cd2188607f6b623bf165db1f288dbf4b55a44cb5d287d2bf3682907d05R346

Also fix "Display post date"; it doesn't work.
Screen Shot 2021-03-15 at 10 45 56

**Comment by contactashish13** [comment]
@htmgarcia `get_coauthors` seems to be a wrapper around `get_multiple_authors`. Do you still want me to use `get_multiple_authors` instead?

```
if (!function_exists('get_coauthors')) {
    function get_coauthors($post_id = 0)
    {
        return get_multiple_authors($post_id);
    }
}
```

Also, should I fix post date as part of another issue or the same issue?

**Comment by htmgarcia** [comment]
Use the new class, please.

The date issue is a bug introduced in this PR. When enabling "Display post date", a comma is outputted only. Please fix it through this PR.

### Develop branch

Screen Shot 2021-03-15 at 11 26 08


### issue-143 branch

Screen Shot 2021-03-15 at 11 26 50

**Comment by contactashish13** [comment]
@htmgarcia have addressed both points.

**Comment by htmgarcia** [comment]
Perfect, @contactashish13!

**Pull request merged**
