### PR TITLE
fix #391: More options for the order of posts

### LINKED ISSUE #391: More options for the order of posts
Screen Shot 2021-03-26 at 4 24 39 PM

### PR DESCRIPTION
**Pull request by contactashish13**
#391 

image

### CODE REVIEW

**Comment by htmgarcia** [comment]
@contactashish13 please update the PR to solve the conflicts.

**Comment by contactashish13** [comment]
@htmgarcia done

**Comment by htmgarcia** [comment]
Thanks @contactashish13 ! This looks promising.

These needs a fix, please:

- Post ID Ascending generates a different result in front. Admin looks fine.
- Not sure about Menu order. All posts are 0 in my database even when adding posts to menus. Am I missing something?
- Author ordering takes in consideration the core single author right? About posts with multiple authors through PublishPress Authors plugin, we should take the first author listed.
Screen Shot 2021-03-31 at 22 27 59

**Comment by contactashish13** [comment]
@htmgarcia have fixed the issue with ID and multiple authors. I'm not sure of menu_order either as it shows them in the correct order at my end but I don't have too many posts. But it should work nevertheless as nothing special needs to be done besides passing menu_order to the query

**Comment by htmgarcia** [comment]
@contactashish13 [this line](https://github.com/publishpress/PublishPress-Blocks/pull/406/commits/2d60189fa29c0f22e039d68cad944263f7d4a210#diff-e80a99cd2188607f6b623bf165db1f288dbf4b55a44cb5d287d2bf3682907d05R664) is causing a few issues in frontend, including disappearing menu widgets in and making home page 404. Once is commented, the problem is solved. Happened with all the themes I tested, including core ones.

Screen Shot 2021-04-01 at 22 08 16

Screen Shot 2021-04-01 at 22 08 33

Please fix this.

**Comment by contactashish13** [comment]
@htmgarcia I can't seem to reproduce the error at my end. I thought it could be something to do with the PublishPress Authors being deactivated but that does not cause a problem either. I don't see any errors in the logs. Any suggestions?

**Comment by contactashish13** [comment]
@htmgarcia I have tried to fix it. Can you please check?

**Comment by htmgarcia** [comment]
Thanks @contactashish13 !

**Pull request merged**
