### PR TITLE
fix #372: Pages support

### LINKED ISSUE #372: Pages support
https://github.com/publishpress/PublishPress-Blocks/issues/194#issuecomment-803187625

### PR DESCRIPTION
**Pull request by contactashish13**
#372 

The sidebar will look like this (with categories and tags missing):

image

### CODE REVIEW

**Comment by htmgarcia** [comment]
Thanks @contactashish13 

Please fix this:
- Update to React 16.14.0 in your dev environment and recompile JS
- "Display Post Author" not working when Post type is "Page" in admin

**Comment by htmgarcia** [comment]
Don't forget to update develop branch as well.

**Comment by contactashish13** [comment]
@htmgarcia have fixed this.

**Comment by htmgarcia** [comment]
Thanks @contactashish13! One more issue to fix, please: admin display pages, frontend display posts.

### Admin
Screen Shot 2021-03-24 at 11 51 40

### Frontend
Screen Shot 2021-03-24 at 11 51 59

**Comment by contactashish13** [comment]
@htmgarcia done!

**Comment by htmgarcia** [comment]
@contactashish13 one last minor issue to fix, please:
```
Notice: Undefined index: postType in /wp-content/plugins/advanced-gutenberg/assets/blocks/recent-posts/block.php on line 87

Notice: Undefined index: postType in /wp-content/plugins/advanced-gutenberg/assets/blocks/recent-posts/block.php on line 96
```

To reproduce: 
- Install version 2.5.7
- Create a new Recent Posts block
- Update to this PR
- Preview Recent Posts block in frontend (without editing)

**Comment by contactashish13** [comment]
@htmgarcia fixed it

**Comment by htmgarcia** [comment]
Thanks @contactashish13!

**Pull request merged**
