### PR TITLE
fix #646: When post type is "products", the author filter doesn't work in editor

### LINKED ISSUE #646: When post type is "products", the author filter doesn't work in editor

### PR DESCRIPTION
**Pull request by contactashish13**
#646

### CODE REVIEW

**Comment by contactashish13** [comment]
@htmgarcia this should fix the issue. I have tested with multiple CPTs including products and regular posts.

**Comment by htmgarcia** [comment]
Thanks @contactashish13 ! There is an error when choosing Products as Post type and filtering by a specific author. PublishPress Authors is enabled:
```
{
  "code": "internal_server_error",
  "message": "<p>There has been a critical error on this website.</p><p><a href=\"https://wordpress.org/support/article/faq-troubleshooting/\">Learn more about troubleshooting WordPress.</a></p>",
  "data": {
    "status": 500
  },
  "additional_errors": []
}
```
The block preview loads forever in the editor.

**Comment by contactashish13** [comment]
@htmgarcia have fixed this. One error I was getting in my logs was below:

```
PHP Warning:  reset() expects parameter 1 to be array, string given in \blocks\recent-posts\block.php on line 1116
```
Have fixed that.

**Comment by htmgarcia** [comment]
@contactashish13 sorry, doesn't work when PublishPress Authors is activated.

**Comment by contactashish13** [comment]
@htmgarcia it works for me. I don't see any errors either. For products, the behavior will be the same whether Authors is on or off. 

Can you please mention what you get so that I can try to reproduce it at my end?

**Comment by htmgarcia** [comment]
@contactashish13 in a second test with Authors enabled, the result is inconsistent in frontend. It worked for one user but not for another:

https://user-images.githubusercontent.com/4999794/127526853-e6328c99-f3bb-4dbf-b3e5-010b94ac7f61.mov

**Comment by contactashish13** [comment]
@htmgarcia can you please check with my latest commit? It seems to work at my end.

**Comment by htmgarcia** [comment]
@contactashish13 that seems to solve the issue with Products, however when testing with a CPT, selecting a specific author (admin in my test) doesn't retrieve any result even when all the movie posts belongs to admin. Only happens when PublishPress Authors is enabled (same result in editor and frontend). Sorry to be a pain.
Screen Shot 2021-08-03 at 11 23 28
Screen Shot 2021-08-03 at 11 23 55

**Comment by contactashish13** [comment]
@htmgarcia below is a breakdown of the existing behavior:

1. when PPA is **active**, the search is performed **only** on the post meta `ppma_authors_name`
2. when PPA is **not active**, the search is performed **only** on the posts `author` field

so, when PPA is active and an author that is **defined only in core** is used as the filter, no posts are displayed because we are searching in the post meta. So for this to work I believe one of the below scenarios would redress the situation:

1. in the filter drop down, do not show the core authors when PPA is active and show only those that are defined in PPA
OR
2. (may not be feasible) change PPA so that when it is activated it "copies" the core author into the post meta field

Let me know your thoughts on this.

PS - I have fixed the code for some consistency issues.

**Comment by htmgarcia** [comment]
Thanks @contactashish13 ! Let's go with option 1. 

> in the filter drop down, do not show the core authors when PPA is active and show only those that are defined in PPA

**Comment by contactashish13** [comment]
@htmgarcia done! 

PS - It took me sometime to figure out that I had added the core users as PPA authors and then had to delete them from there to make this work.  I don't know how likely it is for users to get confused like I did but just wanted to mention this.

@andergmartins just a suggestion: while deleting a PPA author that is tied to a core user, it does not tell me that the core user will not get deleted. Maybe a line that says that could make users less anxious :)

**Comment by htmgarcia** [comment]
@contactashish13 that last commit solved the last issue. Thanks! 

PS. I'm not merging for now due we have a pending release before this.

**Comment by andergmartins** [comment]
> @htmgarcia done!
> 
> PS - It took me sometime to figure out that I had added the core users as PPA authors and then had to delete them from there to make this work. I don't know how likely it is for users to get confused like I did but just wanted to mention this.
> 
> @andergmartins just a suggestion: while deleting a PPA author that is tied to a core user, it does not tell me that the core user will not get deleted. Maybe a line that says that could make users less anxious :)

Thanks, @contactashish13. I added a ticket for that 👍

**Pull request merged**
