### PR TITLE
fix #383: Option to include the time in the layout

### LINKED ISSUE #383: Option to include the time in the layout
example here:
Screen Shot 2021-03-26 at 12 40 50 PM

### PR DESCRIPTION
**Pull request by contactashish13**
#383 

image

### CODE REVIEW

**Comment by htmgarcia** [comment]
@contactashish13 please update your PR to solve the conflict.

**Comment by contactashish13** [comment]
@htmgarcia done

**Comment by htmgarcia** [comment]
Thanks @contactashish13 !

**Comment by htmgarcia** [comment]
@contactashish13 please update the PR again and output time only when both: date and time are enabled. 
https://github.com/publishpress/PublishPress-Blocks/commit/31459b30e5e142aa6d74bfcbdec0f73108398b1f

**Pull request merged**
