### PR TITLE
Call top-notice logic via own function

### PR DESCRIPTION
**Pull request by jmslbam**
Hi devs! 

I found that calling both `load resize` in one go `$(window).on('load resize')` with this top notice in an anonymous call breaks JS on the WP dashboard. This because Woocommerce loads `jquery.flot.resize.js` and messes with the 'resize' logic.

h undefined flot resize

Wrapping this logic in it's own function and calling that, resolves it and doesn't break any backwards compatibility & it's the least effort to code. Because I don't think Woocommerce will be replacing their whole Tables / Graph javascript package for this fix, you think? I am in the proces of opening a ticket there also, but this fix at least won't make this plugin the cullprit :)

I hope you consider applying this PR.

Thank you in advance,

Jaime Martinez!

Ref: https://github.com/woocommerce/woocommerce/blob/trunk/assets/js/jquery-flot/jquery.flot.resize.js & http://benalman.com/projects/jquery-resize-plugin/

Woocommerce 5.6.0 (latest)
Advanced Gutenberg / Publish Press block: 2.10.3 (latetst)
WordPress: 5.8 (latest)
No other plugins active.

### CODE REVIEW

**Comment by htmgarcia** [comment]
@jmslbam thanks for your contribution!

I'm not able to reach the error. May I have more details?

In addition, please point the PR to `develop` branch.

**Comment by jmslbam** [comment]
Hi @htmgarcia,

Thank you for looking at the PR. I have written a extended issue ticket in the Woocommerce repo on how to reproduce it.
https://github.com/woocommerce/woocommerce/issues/30598

So having Woo installed is kind of a "pre" ^^

Hope the Woo ticket shine some more light on the issue and that it helps to reproduce the issue. 

If not, please let me know so I can help some more.

Ciao Jaime!

**Comment by jmslbam** [comment]
And I have changed the base branch to `develop`!

**Comment by htmgarcia** [comment]
@jmslbam thanks! I was able to reproduce the issue in a second try, however the PR generates this cropped effect on load (by going directly to Blocks menu). It seems like if the load is not taking effect.
Screen Shot 2021-08-30 at 17 07 27

**Comment by jmslbam** [comment]
Ah, then I will check that page and tweak the code!
Currently packing for a trip home and will be online again next week.

**Comment by htmgarcia** [comment]
@jmslbam we really appreciate it!

**Comment by jmslbam** [comment]
Hi @htmgarcia, sorry the the wait and thank you for you patience :) It was still on my list to do.

I merge the latest `develop` branch in this PR and adjust the code. I checked the purple banner and now it's positioned correct.

I even added a proper check to reset the margin on smaller screen, other wise it would show a bit to much whitespace when you starter on a larger screen and resized it to a smaller screen. No show-stopper but I noticed it and made a tweak.

Kinds regards,

Jaime Martinez

**Comment by htmgarcia** [comment]
Thanks @jmslbam ! The last commit did the trick.

**Comment by jmslbam** [comment]
Thank you for picking it up so quickly!

**Pull request merged**
