### PR TITLE
fix #441: block visibility schedule

### LINKED ISSUE #441: Allow users to schedule block visibility
Screen Shot 2021-04-12 at 11 20 19 AM

### PR DESCRIPTION
**Pull request by contactashish13**
#441 

This is how it looks:

image

### CODE REVIEW

**Comment by htmgarcia** [comment]
Thanks @contactashish13 ! This is a great start! 

A few requests, please

1. In my tests the block is not being displayed in frontend according with the day time I setup
2. The calendar is using the timezone defined in WordPress General settings?
3. May we enable the feature for all the blocks
4. If we don't choose a date for "Stop showing", let's keep these fields blank or disabled unless we choose a date, please (the block should be displayed forever)

**Comment by contactashish13** [comment]
@htmgarcia I have addressed the issues you mentioned. The user can `Reset` the calendar to unselect a "stop showing" date.

**Comment by htmgarcia** [comment]
Thanks @contactashish13 !

May you confirm if the calendar is using the timezone defined in WordPress General settings?

When I choose both date times, start and stop, it works as expected. Nice job! However it doesn't show the block when I only modify the start date.

In a second case, I get this error when I just enable block scheduling without choosing any date time (start and stop).
`Fatal error: Uncaught Error: Call to a member function getTimestamp() on bool in /wp-content/plugins/advanced-gutenberg-pro/incl/advanced-gutenberg-main.php on line 4612`

Maybe is due some blocks, the attributes `bvEnabled`, `bvDateFrom` and `bvDateTo` are not being added to all the blocks. Works fine with Paragraphs. Checked through Code editor in Content Display and Images Slider blocks.

I'm using PHP 7.4.1

**Comment by contactashish13** [comment]
@htmgarcia 

> May you confirm if the calendar is using the timezone defined in WordPress General settings?

As there is no parameter in the DateTimePicker to specify a timezone, I guess it is timezone agnostic. My assumption is that the dates selected there are dates in the user's current timezone whatever it might be. So, while deciding whether or not to render the block on the front end, I use the current date in the user's timezone for comparison. It seems to work with whatever timezone I choose.

https://github.com/publishpress/PublishPress-Blocks/pull/684/commits/a137683779d3051b0edf960492474f04cf25cc1d#diff-48138e99a9c02e19da943fd0142428c28ef5342ad8e32f1b5554ac10d706a25bL4601-R4612

> Please note the attributes bvEnabled, bvDateFrom and bvDateTo are not being added to all the blocks. Works fine with Paragraphs. Checked through Code editor in Content Display and Images Slider blocks.

Sorry, I had checked with the pro blocks only and it seemed to be working well there. For this to work with the free blocks (with the Free plugin activated), I had to change the `blocks-pro.js` to load in the header and not in the footer otherwise the `blocks.registerBlockType` filter does not get called. I hope that doesn't create a problem elsewhere. Please let me know if it does.

> In a second case, I get this error when I just enable block scheduling without choosing any date time (start and stop).

Have fixed this.

**Comment by htmgarcia** [comment]
@contactashish13 I appreciate the setting integration in Pro.
The start/stop works fine in my end, however still is not consistent. I share some feedback.

If I reset the stop date time picker, and try click "Update" button, I got a "Updating failed" error at random times.
Screen Shot 2021-08-10 at 18 52 33
Once I'm able to save post changes, in front I see `Fatal error: Uncaught Error: Call to a member function getTimestamp() on bool in /wp-content/plugins/advanced-gutenberg-pro/incl/advanced-gutenberg-main.php on line 4604`. Even if I can't replicate the "Updating failed" error, I see the issue in frontend.

The start/show doesn't work consistently in other blocks in comparison with Paragraph blocks. As example, with Testimonials at first try didn't worked due the `bvEnabled`, `bvDateFrom` and `bvDateTo` attribuites weren't added.

**Comment by contactashish13** [comment]
@htmgarcia 

Without changing the code, I went into a post added a Testimonial block, enabled the visibility and clicked on update. I see no errors on the backend or the front end and the block is visible.

`Fatal error: Uncaught Error: Call to a member function getTimestamp() on bool in /wp-content/plugins/advanced-gutenberg-pro/incl/advanced-gutenberg-main.php on line 4604` can only happen when `bvDateFrom` does not exist but I have ensured that as soon as you enable the block, `bvDateFrom` gets set. Maybe I'm missing a use case.

Can you possibly share the steps you followed so that I can reproduce with exactly those? 

Just to confirm, do all use cases work consistently with Paragraphs and not with custom blocks or is the behavior inconsistent with any core, free, pro block?

**Comment by htmgarcia** [comment]
@contactashish13 paragraph is the more consistently case. With other non-core blocks the tests were inconsistent. 

About the inconsistencies in other blocks, probably was due dates may include seconds higher to zero. As example: `2021-08-11T19:49:33` which means 7:49 pm with 33 seconds. Is possible to figure out a way to force seconds to be always `00`? 

I correct myself: the "Update failed" error seems was caused by another plugin.

**Comment by contactashish13** [comment]
@htmgarcia I've added a commit to reset the seconds. I tested with a few more non core blocks and I wasn't able to reproduce the scenario where the attributes do not get added to the block. Let me know if there are some specific steps I need to follow for this.

**Comment by htmgarcia** [comment]
@contactashish13 according to the last test, the block is displayed one minute later. I double checked timezone and time was in sync with my computer.

Same delay happens to stop time. 

https://user-images.githubusercontent.com/4999794/129399755-c9996421-31f3-475c-8a36-c4d56ca5030c.mov

**Comment by htmgarcia** [comment]
The attributes were added to other blocks without problems.

**Comment by contactashish13** [comment]
@htmgarcia sounds good! Have fixed the reported issue. It was showing for a minute extra as well and I've fixed that too.

**Comment by htmgarcia** [comment]
@contactashish13 sorry for being a pain, I still notice randomly seconds on the date time attributes. As example: 2021-08-16T13:03:13 instead of 2021-08-16T13:03:00

In other tasks, please validate the code in Free repository to work only when Pro is detected. It can be done through a constant exclusive in Pro repository in combination with a method stored in Pro.

Sample area to validate the output is https://github.com/publishpress/PublishPress-Blocks/pull/684/files#diff-a70ccaa1c88979cc421bd63f1b199aca60156c51710b3e95a70a7289a7972670R300-R322

**Comment by contactashish13** [comment]
@htmgarcia the seconds in the attributes will not affect the functionality because I'm resetting them to 0 on the server side when rendering the block. Keeping that in mind, do you still want this done because this may be overkill?

> In other tasks, please validate the code in Free repository to work only when Pro is detected. It can be done through a constant exclusive in Pro repository in combination with a method stored in Pro.

I have added this with the constant.

**Comment by htmgarcia** [comment]
@contactashish13 thanks! About the seconds as zero, it works much better now. 

I get a fatal error in frontend and when trying to save in admin got the "Updating failed" message when resetting the "Start showing" while keeping a future date time for "Stop showing".
Screen Shot 2021-08-18 at 15 23 50

`Fatal error: Uncaught Error: Call to a member function setTime() on bool in /wp-content/plugins/advanced-gutenberg-pro/incl/advanced-gutenberg-main.php on line 4594`

Here we have some room to validate both date time fields to avoid errors, I think. Same case when resetting both date time fields.

In addition, may I add a new request for a recurring field. It will be a toggle that will take start and stop date time fields (but ignoring the year) to display the block automatically every year.

**Comment by contactashish13** [comment]
@htmgarcia done! I have assumed that the dateFrom is always necessary even if dateTo is optional. Do you think not having a dateFrom and only having a dateTo could be a likely use case?

Have added monthly (ignore year and month) and yearly (ignore year) for recurrence. I was tempted to add daily too (use only time part) but wasn't sure of the use case. I believe both dates are mandatory for this to work.

**Comment by htmgarcia** [comment]
@contactashish13 may we take in consideration this case scenario, please:
- When `bvDateFrom` is `null` but `bvDateTo` is not null (as example: `2021-08-19T11:22:00`), let's stop showing the block at that date time... or maybe make the reset set current date in `bvDateFrom` attribute instead of `null`?

Adding recurring moth option is a great suggestion! 

Now I'm testing with third party plugin blocks. When [Kadence](https://wordpress.org/plugins/kadence-blocks/) is enabled, it creates an error in front:
`Fatal error: Uncaught TypeError: Argument 1 passed to wpmlcore_7207_fix_kadence_form_block() must be of the type array, null given, called in /wp-includes/class-wp-hook.php on line 305 and defined in /Users/valentingarcia/Local Sites/wp-58/app/public/wp-content/plugins/kadence-blocks/dist/init.php on line 829`

The error disappears when "Enable block visibility schedule" is disabled.

**Comment by contactashish13** [comment]
@htmgarcia have added support for the from date to be null so that the block keeps showing till the to date.

For the issue with Kadence, here is what I've discovered:
- if we change the signature of [our method](https://github.com/publishpress/PublishPress-Blocks/blob/master/src/incl/advanced-gutenberg-main.php#L4540) to `array $block`, which is the same signature as Kadence we get the same error
- if we change the signature of the [method in Kadence](https://plugins.trac.wordpress.org/browser/kadence-blocks/trunk/dist/init.php#L829) to `$block` instead of `array $block` or `array $block = null` no error is thrown and everything works properly
- if I add debug logs over the stack I don't see any instance of passing a `null` e.g. [here](https://core.trac.wordpress.org/browser/tags/5.8/src/wp-includes/blocks.php#L827) `$parsed_block` is not null but an array

I'm confused as to what null object is being passed because in a post that has 1 block, only 1 block is passed to the `render_block_data` filter according to my debugs.

**Comment by contactashish13** [comment]
@htmgarcia In my testing the block behaves exactly as expected when
- both from and to are specified
- only from is specified
- only to is specified


PS - in 5.8 the SelectControls look weird. This happens for all SelectControls as you can see below:

image
image

**Comment by htmgarcia** [comment]
btw, the select looks fine in my end

**Comment by contactashish13** [comment]
@htmgarcia no success with Kadence yet. Couldn't debug why the block is null when it is not. I'll try again next week; there must be something obvious I'm missing

**Comment by contactashish13** [comment]
@htmgarcia 

- I created a new post, added a new paragraph block with visibility and it worked perfectly fine without throwing the error in Kadence.
- I went back to an old post that had only a paragraph tag with visibility and that was throwing the error - it continued to throw an error. Using the code editor I see that it has only one block but in the `render_block_data` it appears to be showing 2 blocks - one is the paragraph block and another which is a null block.
- I removed the paragraph block and created a new one with visibility. Everything worked.

So it looks like somehow my post had a ghost block that was not showing either in the code editor or in the block list view but was causing a problem in the `render_block_data` hook. I have not been able to replicate how this happens despite adding/removing blocks at random so I'm not sure how to resolve this.

**Comment by htmgarcia** [comment]
@contactashish13 that ghost block could be the one added automatically? 
Screen Shot 2021-09-09 at 11 04 57
Try enabling a setting from Blocks > Settings > Remove Autop, and see if makes a difference.

**Comment by contactashish13** [comment]
@htmgarcia I cannot replicate it now no matter what blocks I add or remove, with or without the autop setting enabled. The problematic post last week was a result of deleting a lot of extra blocks and now that same approach does not work! :confounded:

**Comment by htmgarcia** [comment]
@contactashish13 please update your branch to solve the conflicts.

**Comment by contactashish13** [comment]
@htmgarcia done!

**Pull request closed without merging**
