### PR TITLE
fix #194: Custom Post Type support

### LINKED ISSUE #194: Custom Post Type support
Requested by a user: https://wordpress.org/support/topic/custom-post-types-386/

Latest-news-from-custom-post-type

### PR DESCRIPTION
**Pull request by contactashish13**
#194 

This is how I have tested it. Created a CPT called `movies` and its taxonomies `genre`, `lang` and `yearss`

image

### CODE REVIEW

**Comment by htmgarcia** [comment]
Awesome job, @contactashish13 ! In general works as expected. 

I have a few requests that needs a fix, please:

- When editing an existing Content Display block, in browser console I see this 404 error: `GET https://wordpress-426925-1874115.cloudwaysapps.com/wp-json/wp/v2/types/undefined?context=edit&_locale=user [HTTP/2 404 Not Found 1957ms]`
- When choosing a Post Type (custom and core), filters takes some time to refresh and this (probably) cause the block in editor to refresh twice. I can see the taxonomy fields from previous selected Post Type for about 5 seconds before they change. Is possible to improve this?
- The featured images are not shown in editor for CPT. The placeholder image is displayed always. 
- Please exclude media from post types. Make room in the code involved (maybe an array) to easily exclude later other common post types in case we reach display issues.

**Comment by contactashish13** [comment]
@htmgarcia I have tried to address your concerns. Can you please test?

**Comment by htmgarcia** [comment]
@contactashish13 much better, thanks!

One final thing. Exclude posts didn't worked for CPT when editing an existing Content Display block that was previously displaying regular posts. Later worked as expected after save and refresh. Are able to reproduce this? If that's the case, please fix it.

**Comment by contactashish13** [comment]
@htmgarcia here are the steps I tried and I was not able to reproduce this. Can you mention the steps you used in case they are different?
- use develop branch, create block with regular posts, exclude a post, save the post
- use #194 branch, edit the block (it works)
- exclude another post (it works)
- change post type to CPT
- exclude works as expected (suggestions show up and post is excluded)

**Comment by htmgarcia** [comment]
@contactashish13 I'm not able to reproduce the issue. Maybe was a one time random scenario.

**Pull request merged**
