### PR TITLE
fix #486: display custom taxonomies

### LINKED ISSUE #486: Display custom taxonomies
Once #194 is done, let's allow to display custom taxonomies like we do with tags

### PR DESCRIPTION
**Pull request by contactashish13**
#486

### CODE REVIEW

**Comment by htmgarcia** [comment]
@contactashish13 the block is broken when switching to a CPT. There is an error in console:
`TypeError: showCustomTaxList is undefined`

**Comment by contactashish13** [comment]
@htmgarcia here are the steps I followed:

- created a post with `post` and saved it
- refreshed the edit, switched it to using a CPT and got the below error, which is different from yours

image

- after my [changes](https://github.com/publishpress/PublishPress-Blocks/pull/495/commits/38990d8bac0c701e35487def93b357c138cd698f) the above error disappears and the box is no longer broken

Can you please confirm you see the same behavior and if not, could you please mention the steps?

**Comment by htmgarcia** [comment]
@contactashish13 I don't see any error in my end. The custom taxonomies are displayed and linked correctly. 

Just one small fix please: the "Display these taxonomies" filter by the slugs, not the titles. 
Screen Shot 2021-05-04 at 19 50 56

**Comment by contactashish13** [comment]
@htmgarcia fixed this and also addressed problems with special characters in tax names.

**Comment by htmgarcia** [comment]
Thanks @contactashish13 !

**Pull request merged**
