### PR TITLE
fix #472: Improvements to use of custom styles

### LINKED ISSUE #472: Improvements to use of custom styles
Can we make them more visible in the admin area? Maybe a dropdown somewhere?

Using the "Advanced" box isn't easy:
Screen Shot 2021-04-21 at 10 27 06 AM

### PR DESCRIPTION
**Pull request by contactashish13**
#472

### CODE REVIEW

**Comment by htmgarcia** [comment]
@contactashish13 the style is applied in editor for paragraphs. Nice one! May we support all the blocks? (not only the PublishPress Blocks). Very likely this will require to modify the Advanced > Additional CSS class(es) field instead of the customStyle attribute. Please take in consideration backward compatibility (deprecation) for paragraphs blocks already using custom style setting if required.

**Comment by contactashish13** [comment]
@htmgarcia if I merely remove all the checks that check for `core/paragraph` this is how some of the blocks render on the backend:

image

and on the front end

image

Some, like pullquote, don't render the background color because it is overridden by other styles but if we adjust the styles in the plugin's settings and add an `!important` it renders correctly:

image

I did not fiddle with the Advanced > Additional CSS class(es) and it more or less works. What do you suggest?

**Comment by htmgarcia** [comment]
@contactashish13 I see your point. Please remove the checks for paragraphs. We'll test and decide based on that.

**Comment by contactashish13** [comment]
@htmgarcia done!

**Comment by htmgarcia** [comment]
@contactashish13 please undo the last commit and in addition to paragraph, enable the custom styles to these blocks:
- heading
- list
- code
- classic
- preformatted
- table
- columns
- group

**Comment by contactashish13** [comment]
@htmgarcia done!

**Comment by htmgarcia** [comment]
Thanks, @contactashish13 !

**Pull request merged**
