### PR TITLE
fix #146: multiple category support

### LINKED ISSUE #146: Multiple category support
Suggestion from the forum: https://wordpress.org/support/topic/suggestions-for-recent-posts-block/

### PR DESCRIPTION
**Pull request by contactashish13**
#146 

This is how it looks:

image

### CODE REVIEW

**Comment by contactashish13** [comment]
@htmgarcia can you please review this?

**Comment by htmgarcia** [comment]
Thank you very much, @contactashish13! The multiple category selection works fine and seems to be compatible with previously created blocks. I like how this PR follows the "Latest Posts" core block UI for categories selection.

Just a small request, is possible to display in autocompletion the category name instead of the slug? 
### Current result

### Expected result

**Comment by htmgarcia** [comment]
In a second test for existing "Recent Posts" blocks, the category attribute is removed when updating. 

### The source goes from:
`<!-- wp:advgb/recent-posts {"category":"1","changed":true} /-->`

### to:
`<!-- wp:advgb/recent-posts {"changed":true} /-->`

Very likely we need to a deprecation through `deprecated` method to tell to existing blocks that attribute `category` to `categories`.

### Expected result:
`<!-- wp:advgb/recent-posts {"categories":[{"id":1},"changed":true} /-->`

Note: in addition to the id, includes the category name as "value". Is this required? 
`"categories":[{"id":1,"value":"Lorem Ipsum"}`

We appreciate your contribution and feedback, @contactashish13!

**Comment by htmgarcia** [comment]
I correct myself about the expected result. `categories` should only contain the ids and no extra attributes.

### Expected result for 1 category:
`<!-- wp:advgb/recent-posts {"categories":{"1"},"changed":true} /-->`

**Comment by contactashish13** [comment]
@htmgarcia I've added support for using the `name` instead of `slug` and renamed the attribute back to `category` so that the deprecated block isn't required

I'm not sure about https://github.com/publishpress/PublishPress-Blocks/pull/331#issuecomment-789974123 though as the name is required otherwise the suggestions box shows empty like this:

image

**Comment by htmgarcia** [comment]
@contactashish13 thanks for the clarification on the category name. I compared with the Latest Posts core block source and the output is the same. All good here! Thanks.

Just one concern I found and we're all set. While editing blocks created with previous versions of PublishPress Blocks, the category value is removed. For the sake of backward compatibility, I think is necessary to keep the selected category. 

### Block created with version 2.5.6 or older
`category` is available, except when selecting "All"
`<!-- wp:advgb/recent-posts {"category":"1","changed":true} /-->`

### After updating to multiple category support version
`category` is removed
`<!-- wp:advgb/recent-posts {"changed":true} /-->`

### Expected result
The category should not be removed.

**Comment by htmgarcia** [comment]
I think is matter to convert the `category` value to the new format that comes with multiple category.

**Comment by contactashish13** [comment]
@htmgarcia the latest commits address this. We cannot retain the `category` attribute but we can make it forward compatible so that `category` maps into `categories`. I don't think we need a deprecated block for this because it is being handled transparently inside the code.

**Comment by htmgarcia** [comment]
Thanks @contactashish13! The last commit fixed the backward compatibility, however a new issue came up. For each category selected a notice is triggered in frontend and admin.

`Notice: Array to string conversion in /wp-includes/class-wp-query.php on line 776`

In order to see the notice, is required to first edit the page that includes the block and have WP_DEBUG enabled.

Please fix this.

**Comment by contactashish13** [comment]
@htmgarcia thanks for the details. Have fixed it and it now looks good from my side. Can you please review?

**Comment by htmgarcia** [comment]
@contactashish13 all set. Thanks!

**Pull request merged**
